name: mindskape
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  firebase_ui_auth:
  google_sign_in:
  image_picker:
  firebase_storage:
  firebase_auth:
  get: ^4.6.6
  cloud_firestore:
  font_awesome_flutter:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/


