// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB69PaWA0NFX1WHykMcakhRlirEckD3HZA',
    appId: '1:883775755673:web:7a97504a50bf2161bdaf08',
    messagingSenderId: '883775755673',
    projectId: 'mindskape-edf80',
    authDomain: 'mindskape-edf80.firebaseapp.com',
    storageBucket: 'mindskape-edf80.appspot.com',
    measurementId: 'G-P10TQ1S8GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcf12R0xviaqoURCgORjKnotQ7rkLArB0',
    appId: '1:883775755673:android:69759e0a09e825eebdaf08',
    messagingSenderId: '883775755673',
    projectId: 'mindskape-edf80',
    storageBucket: 'mindskape-edf80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt_c0z1bQkVL_Tlgx4TeOigy7_D3E31lU',
    appId: '1:883775755673:ios:70d1c18b07575c9dbdaf08',
    messagingSenderId: '883775755673',
    projectId: 'mindskape-edf80',
    storageBucket: 'mindskape-edf80.appspot.com',
    iosBundleId: 'com.example.mindskape',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt_c0z1bQkVL_Tlgx4TeOigy7_D3E31lU',
    appId: '1:883775755673:ios:946c38ec4f5e4c1bbdaf08',
    messagingSenderId: '883775755673',
    projectId: 'mindskape-edf80',
    storageBucket: 'mindskape-edf80.appspot.com',
    iosBundleId: 'com.example.mindskape.RunnerTests',
  );
}
